# Generated by Django 4.0.1 on 2022-02-04 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amt_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amt_to_be_paid', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.IntegerField()),
                ('education_institution', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('graduation_month', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.educationtype')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=50)),
                ('patient_last_name', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(max_length=1)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_phone_number', models.IntegerField(null=True)),
                ('patient_email', models.CharField(max_length=200, null=True)),
                ('service_location', models.CharField(max_length=500)),
                ('service_start_time', models.TimeField()),
                ('service_end_time', models.TimeField()),
                ('service_needed_sunday', models.BooleanField()),
                ('service_needed_monday', models.BooleanField()),
                ('service_needed_tuesday', models.BooleanField()),
                ('service_needed_wednesday', models.BooleanField()),
                ('service_needed_thursday', models.BooleanField()),
                ('service_needed_friday', models.BooleanField()),
                ('service_needed_saturday', models.BooleanField()),
                ('days_of_service', models.IntegerField()),
                ('care_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.caretaker')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.billingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthcare_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.healthcareprofessional')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.securityquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience_required', models.IntegerField()),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.educationtype')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.servicetype'),
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.servicerequest'),
        ),
    ]
