# Generated by Django 4.0.2 on 2022-02-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0003_accountstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
