# Generated by Django 4.0.1 on 2022-02-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0004_jobposting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.IntegerField()),
                ('education_institution', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('graduation_month', models.IntegerField()),
                ('years_of_experience', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.educationtype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.jobposting')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.servicetype')),
            ],
        ),
    ]
