# Generated by Django 4.0.1 on 2022-02-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0005_hpjobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTakerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('date_requested', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
