# Generated by Django 4.0.1 on 2022-02-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0006_caretakerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretakerrequest',
            name='date_requested',
            field=models.DateTimeField(),
        ),
    ]
