# Generated by Django 4.0.1 on 2022-02-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0007_alter_caretakerrequest_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
