# Generated by Django 4.0.1 on 2022-02-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0008_alter_staffmember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerrequest',
            name='first_name',
            field=models.CharField(default='first name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caretakerrequest',
            name='last_name',
            field=models.CharField(default='last name', max_length=50),
            preserve_default=False,
        ),
    ]
