# Generated by Django 4.0.1 on 2022-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0010_caretakerrequest_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='flexible_hours',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='hours_of_service_daily',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='hp_gender_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='hp_max_age',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='hp_min_age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
