# Generated by Django 4.0.1 on 2022-02-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0011_hpjobapplication_first_name_and_more'),
        ('agency_api', '0011_servicerequest_flexible_hours_and_more'),
    ]

    operations = [
    ]
