# Generated by Django 4.0.1 on 2022-02-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0011_hpjobapplication_is_approved_and_more'),
    ]

    operations = [
        
    ]
