# Generated by Django 4.0.1 on 2022-02-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0012_merge_20220221_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpjobapplication',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hpjobapplication',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hours_of_service_daily',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hp_max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hp_min_age',
            field=models.IntegerField(null=True),
        ),
    ]
