# Generated by Django 4.0.1 on 2022-02-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0013_alter_hpjobapplication_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='patient_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='patient_phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
