# Generated by Django 4.0.1 on 2022-02-21 06:01

import agency_api.utils.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0014_alter_servicerequest_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='phone_number',
            field=models.BigIntegerField(validators=[agency_api.utils.validation.validate_phone]),
        ),
        migrations.AlterField(
            model_name='caretakerrequest',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caretakerrequest',
            name='phone_number',
            field=models.BigIntegerField(validators=[agency_api.utils.validation.validate_phone]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='patient_phone_number',
            field=models.BigIntegerField(null=True, validators=[agency_api.utils.validation.validate_phone]),
        ),
    ]
