# Generated by Django 4.0.1 on 2022-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0016_alter_servicerequest_service_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
