# Generated by Django 4.0.1 on 2022-03-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0017_alter_healthcareprofessional_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpjobapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hpjobapplication',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
