# Generated by Django 4.0.1 on 2022-02-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0012_hpjobapplication_first_name_and_more'),
        ('agency_api', '0017_alter_healthcareprofessional_phone_number_and_more'),
    ]

    operations = [
    ]
