# Generated by Django 4.0.1 on 2022-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0017_alter_healthcareprofessional_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
