# Generated by Django 4.0.1 on 2022-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0018_healthcareprofessional_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareprofessional',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='healthcareprofessional',
            name='is_pending',
        )
        
    ]
