# Generated by Django 4.0.1 on 2022-03-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0018_hpjobapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
