# Generated by Django 4.0.1 on 2022-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0019_remove_healthcareprofessional_is_approved_and_more'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
