# Generated by Django 4.0.1 on 2022-03-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0019_servicerequest_is_active_servicerequest_is_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='is_active',
            new_name='is_completed',
        ),
    ]
