# Generated by Django 4.0.1 on 2022-03-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0020_rename_is_active_servicerequest_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=32.45, max_digits=5),
            preserve_default=False,
        ),
    ]
