# Generated by Django 4.0.1 on 2022-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0020_hpjobapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpjobapplication',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
