# Generated by Django 4.0.1 on 2022-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0021_hpjobapplication_is_approved'),
    ]

    operations = [
       
    ]
