# Generated by Django 4.0.1 on 2022-03-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0021_alter_servicerequest_patient_gender'),
        ('agency_api', '0021_servicetype_hourly_rate'),
    ]

    operations = [
    ]
