# Generated by Django 4.0.1 on 2022-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0022_merge_20220308_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
            preserve_default=False,
        ),
    ]
