# Generated by Django 4.0.1 on 2022-03-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0022_merge_20220308_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='start_date',
            field=models.DateField(default='2022-03-15'),
            preserve_default=False,
        ),
    ]
