# Generated by Django 4.0.1 on 2022-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0023_servicerequest_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_friday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_monday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_saturday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_sunday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_thursday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_tuesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='end_time_wednesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_friday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_monday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_saturday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_sunday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_thursday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_tuesday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='hours_wednesday',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_friday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_monday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_saturday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_sunday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_thursday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_tuesday',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='serviceassignment',
            name='start_time_wednesday',
            field=models.TimeField(null=True),
        ),
    ]
