# Generated by Django 4.0.1 on 2022-03-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0024_serviceassignment_end_time_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_friday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_monday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_saturday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_sunday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_thursday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_tuesday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='hours_wednesday',
        ),
    ]
