# Generated by Django 4.0.1 on 2022-03-20 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0025_remove_serviceassignment_hours_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_friday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_monday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_saturday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_sunday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_thursday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_tuesday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='end_time_wednesday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_friday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_monday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_saturday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_sunday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_thursday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_tuesday',
        ),
        migrations.RemoveField(
            model_name='serviceassignment',
            name='start_time_wednesday',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.serviceassignment')),
            ],
        ),
    ]
