# Generated by Django 4.0.1 on 2022-03-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0023_healthcareprofessional_hourly_rate'),
        ('agency_api', '0026_remove_serviceassignment_end_time_friday_and_more'),
    ]

    operations = [
    ]
