# Generated by Django 4.0.1 on 2022-03-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0027_merge_20220327_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='earliest_work_time',
            field=models.TimeField(default='06:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetype',
            name='latest_work_time',
            field=models.TimeField(default='18:00:00'),
            preserve_default=False,
        ),
    ]
