# Generated by Django 4.0.1 on 2022-04-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0028_servicetype_earliest_work_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaccount',
            name='amt_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='billingaccount',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='serviceentry',
            name='healthcare_professional',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='agency_api.healthcareprofessional'),
            preserve_default=False,
        ),
    ]
