# Generated by Django 4.0.1 on 2022-04-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0031_alter_serviceentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('healthcare_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency_api.healthcareprofessional')),
            ],
        ),
    ]
