# Generated by Django 4.0.1 on 2022-04-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0032_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_of_payment']},
        ),
    ]
