# Generated by Django 4.0.1 on 2022-04-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_api', '0034_pendingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(),
        ),
    ]
